[project]
name = "storage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pydantic>=2.11.3",
    "pymongo>=4.12.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.5",
]
